# Generated by Django 4.2.18 on 2025-03-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('avatar', models.CharField(default='default_avatar', max_length=100)),
                ('primary_language', models.CharField(choices=[('igbo', 'Igbo'), ('hausa', 'Hausa'), ('yoruba', 'Yoruba')], max_length=20)),
                ('secondary_languages', models.JSONField(default=list)),
                ('language_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('daily_goal_minutes', models.IntegerField(default=15)),
                ('preferred_learning_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='afternoon', max_length=20)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
                'db_table': 'child_profile',
            },
        ),
        migrations.CreateModel(
            name='ParentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('app_notifications', models.BooleanField(default=True)),
                ('progress_reports', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('max_daily_screen_time', models.IntegerField(default=60)),
                ('content_difficulty', models.CharField(choices=[('age_appropriate', 'Age Appropriate'), ('challenging', 'Challenging'), ('easy', 'Easy')], default='age_appropriate', max_length=20)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_settings',
            },
        ),
        migrations.CreateModel(
            name='ChildProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_activities', models.JSONField(default=list)),
                ('mastery_percentage', models.FloatField(default=0.0)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='userProfile.child')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningCore.language')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningCore.learningmodule')),
            ],
            options={
                'db_table': 'child_progress',
                'unique_together': {('child', 'module')},
            },
        ),
    ]
