# Generated by Django 5.1.7 on 2025-05-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('category', models.CharField(choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence'), ('culture', 'Culture')])),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('interactive', 'Interactive')])),
                ('content_url', models.TextField()),
            ],
        ),
    ]
