# Generated by Django 5.1.7 on 2025-04-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
